const lombric = [
    {
        name:"lombric1.0",
        image:"./src/assets/img-lombric/lombric1.0.jpg",
    },
    {
        name:"lombric1.1",
        image:"./src/assets/img-lombric/lombric1.1.jpg",
    },
    {
        name:"lombric1.2",
        image:"./src/assets/img-lombric/lombric1.2.jpg",
    },
    {
        name:"lombric1.3",
        image:"./src/assets/img-lombric/lombric1.3.jpg",
    },
    {
        name:"lombric2.0",
        image:"./src/assets/img-lombric/lombric2.0.jpg",
    },
    {
        name:"lombric2.1",
        image:"./src/assets/img-lombric/lombric2.1.jpg",
    },
    {
        name:"lombric2.2",
        image:"./src/assets/img-lombric/lombric2.2.jpg",
    },
    {
        name:"lombric2.3",
        image:"./src/assets/img-lombric/lombric2.3.jpg",
    },
    {
        name:"lombric3.0",
        image:"./src/assets/img-lombric/lombric3.0.jpg",
    },
    {
        name:"lombric3.1",
        image:"./src/assets/img-lombric/lombric3.1.jpg",
    },
    {
        name:"lombric3.2",
        image:"./src/assets/img-lombric/lombric3.2.jpg",
    },
    {
        name:"lombric3.3",
        image:"./src/assets/img-lombric/lombric3.3.jpg",
    },
    {
        name:"lombric4.0",
        image:"./src/assets/img-lombric/lombric4.0.jpg",
    },
    {
        name:"lombric4.1",
        image:"./src/assets/img-lombric/lombric4.1.jpg",
    },
    {
        name:"lombric4.2",
        image:"./src/assets/img-lombric/lombric4.2.jpg",
    },
    {
        name:"lombric4.3",
        image:"./src/assets/img-lombric/lombric4.3.jpg",
    }

]

export default lombric